"""
Django settings for capstone project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import ssl

# Fix SSL certificate verification issues for development
ssl._create_default_https_context = ssl._create_unverified_context

# Load environment variables from .env file
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7t38w67gl69j@dltx41uxo#zfm)k6j4km_qkt#2r@)!g6h0m)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Session Security
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store sessions in database
SESSION_COOKIE_HTTPONLY = False  # Allow JS access for development
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_DOMAIN = None     # Allow for localhost development
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request

# For development - set these to True in production with HTTPS
SESSION_COOKIE_SECURE = False  # Set to True with HTTPS
CSRF_COOKIE_SECURE = False     # Set to True with HTTPS
SECURE_SSL_REDIRECT = False    # Set to True in production

# Allow cross-origin cookies for development
SESSION_COOKIE_SAMESITE = None  # Allow cross-origin requests in development (changed from 'Lax')
CSRF_COOKIE_SAMESITE = None     # Allow cross-origin CSRF tokens (changed from 'Lax')
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name

# File Upload Security
FILE_UPLOAD_PERMISSIONS = 0o644  # Secure file permissions


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',  # OCR and AWS credentials management
    'accounts',
    'patients',
    'appointments',
     'clinic',
    'doctor_availability',
    'medical_documents',
    'medical_requests',
    'security_app',  # Security management
    'systemlogs',  # Audit logging system
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # More secure than True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # React dev server
    "http://localhost:8081",  # React dev server alternative port
    "http://localhost:3000",  # React dev server alternative port
    "http://localhost:5173",  # Vite dev server default port
    "http://localhost:4173",  # Vite preview port
]

# CSRF Trusted Origins for development
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",  # React dev server
    "http://localhost:8081",  # React dev server alternative port
    "http://localhost:3000",  # React dev server alternative port
    "http://localhost:5173",  # Vite dev server default port
    "http://localhost:4173",  # Vite preview port
]

# Disable CSRF for development
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = None

# Disable CSRF protection completely for development  
CSRF_CHECK_DISABLED = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-session-id',  # Allow custom session ID header for development
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'disable_csrf_middleware.DisableCSRFMiddleware',  # Disable CSRF completely for development
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Temporarily disable CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'dev_session_middleware.DevSessionMiddleware',  # Custom session middleware for development
    'systemlogs.middleware.AuditMiddleware',  # Audit logging middleware
    'debug_middleware.DebugMiddleware',  # Add debug middleware after authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'security_app.middleware.SecurityMiddleware',  # Temporarily disable security middleware
]
AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameBackend',  # Custom backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]
ROOT_URLCONF = 'capstone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'medsync',
        'USER':'postgres',
        'PASSWORD':'admin',
        'HOST':'127.0.0.1',
        'PORT':'5432',
        'OPTIONS': {
            'sslmode': 'prefer',  # Enable SSL for database connections
            'connect_timeout': 60,
        },
    }
}

# Cache configuration for OTP storage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Domain URL for email links and media files
DOMAIN_URL = 'http://127.0.0.1:8000'  # Change this to your production domain

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Keep permissive for now
    ],
}

# Email Configuration - SMTP for production emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'jeri.olivarez@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'jeri.olivarez@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', 'your_new_app_password_here')  # Use environment variable
EMAIL_TIMEOUT = 30

# AWS Configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')

# Clinic Configuration
CLINIC_DEFAULT_EMAIL = 'jeri.olivarez@gmail.com'  # Email to receive review notifications

# ===============================
# SMS SERVICE CONFIGURATION
# ===============================

# Semaphore (Philippines SMS Provider) - CONFIGURED
# Your API key: 1d1b9ab6af89e61b3db59d9ab3796906
SEMAPHORE_API_KEY = '1d1b9ab6af89e61b3db59d9ab3796906'

# ===============================
# IPROG SMS API CONFIGURATION (PRIMARY)
# ===============================

# iProg SMS API - Philippines SMS Provider
IPROG_API_TOKEN = os.getenv('IPROG_API_TOKEN', '')
IPROG_API_URL = os.getenv('IPROG_API_URL', 'https://sms.iprogtech.com/api/v1/sms_messages')
IPROG_SMS_PROVIDER = os.getenv('IPROG_SMS_PROVIDER', '0')  # 0 or 1, default: 0

# ===============================
# TWILIO CONFIGURATION FOR OTP (BACKUP)
# ===============================

# Twilio settings - Get these from your Twilio Console
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')  # Your Twilio phone number

# OTP Configuration
OTP_LENGTH = 6
OTP_EXPIRY_MINUTES = 5
OTP_MAX_ATTEMPTS = 3


