"""
Django settings for capstone project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import ssl

# Fix SSL certificate verification issues for development
ssl._create_default_https_context = ssl._create_unverified_context

# Environment detection
import socket
hostname = socket.gethostname()
is_production_server = 'srv' in hostname.lower() or 'lunasync' in hostname.lower()

# Determine environment and load appropriate config
if is_production_server:
    # Production server - load production environment
    if os.path.exists('.env.production'):
        load_dotenv('.env.production')
        print("✅ PRODUCTION: Loaded environment variables from .env.production")
        PRODUCTION = True
        DEBUG = False
    else:
        print("⚠️ PRODUCTION: .env.production file not found")
        PRODUCTION = True
        DEBUG = False
else:
    # Development environment - load development environment
    env_file = os.path.join(Path(__file__).resolve().parent.parent, '.env')
    if os.path.exists(env_file):
        load_dotenv(env_file)
        print("✅ DEVELOPMENT: Loaded environment variables from .env")
        PRODUCTION = os.environ.get('PRODUCTION', 'False').lower() == 'true'
        DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'
    else:
        print("⚠️ DEVELOPMENT: .env file not found, using defaults")
        PRODUCTION = False
        DEBUG = True

print(f"🔧 Environment: {'PRODUCTION' if PRODUCTION else 'DEVELOPMENT'}")
print(f"🐛 Debug Mode: {DEBUG}")
print(f"🖥️ Hostname: {hostname}")

# Encryption key for AES-256 (must be 32 bytes, base64-encoded)
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', None)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(7t38w67gl69j@dltx41uxo#zfm)k6j4km_qkt#2r@)!g6h0m)')

# SECURITY WARNING: don't run with debug turned on in production!
if PRODUCTION:
    DEBUG = False  # Always False in production
else:
    DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'  # Environment-controlled in development

# Dynamic allowed hosts based on environment
if PRODUCTION:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['lunasync.site','www.lunasync.site','31.97.67.53','testserver']
    # Frontend URL for email links in production
    FRONTEND_URL = 'https://lunasync.site'
    # Site configuration for production
    SITE_ID = 1
    SITE_DOMAIN = 'lunasync.site'
    SITE_NAME = 'LunaSync Medical System'
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '*']  # Allow all hosts in development
    # Frontend URL for email links in development
    FRONTEND_URL = 'http://localhost:8080'
    # Site configuration for development
    SITE_ID = 1
    SITE_DOMAIN = 'localhost:8000'
    SITE_NAME = 'LunaSync Medical System (Dev)'

# Security Settings - Environment dependent
if PRODUCTION:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Fix for reverse proxy (nginx) with HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_TZ = True
    
    # Force Django to use HTTPS and correct domain for URL generation
    FORCE_SCRIPT_NAME = None
    PREPEND_WWW = False
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_SAMESITE = 'Strict'
else:
    # Development settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# Session Security
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store sessions in database
SESSION_COOKIE_AGE = 14400  # 4 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_DOMAIN = None     # Allow for localhost development
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name
CSRF_COOKIE_NAME = 'csrftoken'     # Default CSRF cookie name

# File Upload Security
FILE_UPLOAD_PERMISSIONS = 0o644  # Secure file permissions


# Application definition

INSTALLED_APPS = [
    # Keep required Django apps (auth depends on contenttypes):
    'django.contrib.auth',           # ✅ Required for user authentication
    'django.contrib.contenttypes',   # ✅ Required by auth (but we won't use it)
    'django.contrib.sessions',       # ✅ Required for audit logging
    'django.contrib.staticfiles',    # ✅ Required for static files
    'django.contrib.sites',          # ✅ Required for captcha absolute URLs
    
   
    
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'captcha',  # Django simple captcha
    'api',  
    'accounts',
    'patients',
    'appointments',
     'clinic',
    'doctor_availability',
    'medical_documents',
    'medical_requests.apps.MedicalRequestsConfig',
    'security_app',  # Security management
    'systemlogs',  # Audit logging system
    'inventory',  # Medication inventory management
    'sql_query',  # SQL query execution for admin testing
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # More secure than True

# Environment-dependent CORS settings
if PRODUCTION:
    # Production CORS - more restrictive
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else [
        'https://lunasync.site',
        'https://www.lunasync.site'
    ]
    CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else [
        'https://lunasync.site',
        'https://www.lunasync.site'
    ]
    CSRF_USE_SESSIONS = True
    CSRF_CHECK_DISABLED = False
else:
    # Development CORS - only for localhost
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:8080",  # Frontend dev server
        "http://localhost:5173",  # Vite dev server
        "http://127.0.0.1:8080",  # Frontend dev server (IP form)
        "http://127.0.0.1:5173",  # Vite dev server (IP form)
    ]

    # CSRF Trusted Origins for development
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8080",
        "http://localhost:5173",
        "http://127.0.0.1:8080",
        "http://127.0.0.1:5173",
    ]
    
    CSRF_USE_SESSIONS = False
    CSRF_CHECK_DISABLED = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-session-id',  # Allow custom session ID header for development
]

MIDDLEWARE = [
        'corsheaders.middleware.CorsMiddleware',
        'security_app.security_middleware.EncryptionKeyValidationMiddleware',  # Validate encryption key
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',  # Enable CSRF protection
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'security_app.security_middleware.DataAccessAuditMiddleware',  # Audit sensitive data access
        'security_app.security_middleware.SecurityLoggingMiddleware',  # Secure logging
        # 'dev_session_middleware.DevSessionMiddleware',  # Custom session middleware for development
        'systemlogs.middleware.AuditMiddleware',  # Audit logging middleware
        # 'middleware.debug_middleware.DebugMiddleware',
        # 'middleware.dev_session_middleware.DevSessionMiddleware', # Add debug middleware after authentication
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'security_app.middleware.SecurityMiddleware',  # Temporarily disable security middleware
]
AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameBackend',  # Custom backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]
ROOT_URLCONF = 'capstone.urls'

TEMPLATES = [
    { 
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone.wsgi.application'


# Database configuration - Environment dependent
if PRODUCTION and os.environ.get('DATABASE_URL'):
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
        }
    except ImportError:
        # If dj_database_url is not installed, parse manually
        import urllib.parse as urlparse
        url = urlparse.urlparse(os.environ.get('DATABASE_URL'))
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': url.path[1:],
                'USER': url.username,
                'PASSWORD': url.password,
                'HOST': url.hostname,
                'PORT': url.port,
                'OPTIONS': {
                    'sslmode': 'require',  # Enable SSL for database connections
                    'connect_timeout': 60,
                },
            }
        }
elif PRODUCTION:
    # Production database configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':'medsync',
            'USER':'lunasyncuser',
            'PASSWORD':'lunasyncuser@2022',
            'HOST':'127.0.0.1',
            'PORT':'5432',
            'OPTIONS': {
                'sslmode': 'require',  # Enable SSL for database connections
                'connect_timeout': 60,
            },
        }
    }
else:
    # Development database configuration - Use SQLite for simplicity
    # You can override this with DATABASE_URL in your .env file if you prefer PostgreSQL
    database_url = os.environ.get('DATABASE_URL')
    if database_url:
        # If DATABASE_URL is provided in .env, use it (PostgreSQL)
        try:
            import dj_database_url
            DATABASES = {
                'default': dj_database_url.parse(database_url)
            }
        except ImportError:
            # Fallback manual parsing
            import urllib.parse as urlparse
            url = urlparse.urlparse(database_url)
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': url.path[1:],
                    'USER': url.username,
                    'PASSWORD': url.password,
                    'HOST': url.hostname,
                    'PORT': url.port,
                    'OPTIONS': {
                        'sslmode': 'prefer',  # More relaxed SSL for development
                        'connect_timeout': 60,
                    },
                }
            }
    else:
        # Default to SQLite for development
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Cache configuration for OTP storage
# Using database cache to ensure all Gunicorn workers can access the same cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Domain URL for email links and media files
DOMAIN_URL = 'https://lunasync.site'  # Production domain

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Disable CSRF for API views using session authentication
# This is needed because DRF SessionAuthentication enforces CSRF even with @csrf_exempt
from rest_framework.authentication import SessionAuthentication

class CsrfExemptSessionAuthentication(SessionAuthentication):
    def enforce_csrf(self, request):
        return  # To not perform the csrf check previously happening

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'capstone.settings.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication by default
    ],
}

# Email Configuration - SMTP for production emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'medratrics.langgam@gmail.com')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'medratrics.langgam@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'your_new_app_password_here')  # Use environment variable
EMAIL_TIMEOUT = 30

# AWS Configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')

# Clinic Configuration
CLINIC_DEFAULT_EMAIL = os.getenv('EMAIL_HOST_USER', 'medratrics.langgam@gmail.com')  # Email to receive review notifications



# iProg SMS API - Philippines SMS Provider
IPROG_API_TOKEN = os.getenv('IPROG_API_TOKEN', '')
IPROG_API_URL = os.getenv('IPROG_API_URL', 'https://sms.iprogtech.com/api/v1/sms_messages')
IPROG_SMS_PROVIDER = os.getenv('IPROG_SMS_PROVIDER', '0')  # 0 or 1, default: 0


TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')  # Your Twilio phone number

# OTP Configuration
OTP_LENGTH = 6
OTP_EXPIRY_MINUTES = 5
OTP_MAX_ATTEMPTS = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files configuration for production
if PRODUCTION:
    # Use WhiteNoise for serving static files in production
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Determine log file path based on environment
if PRODUCTION:
    LOG_FILE = '/home/lunasynccapstone/LunaSync/django.log'
    # Ensure production log directory exists
    os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
else:
    LOG_FILE = str(LOGS_DIR / 'django.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'api': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'otp_email': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'appointments.email_utils': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Django Simple Captcha Configuration
CAPTCHA_IMAGE_SIZE = (140, 60)  # Slightly larger for better visibility
CAPTCHA_TIMEOUT = 5  # 5 minutes
CAPTCHA_LENGTH = 4
CAPTCHA_FONT_SIZE = 32  # Larger font for better readability
CAPTCHA_TEST_MODE = False

# Basic captcha settings that work across environments
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
CAPTCHA_FILTER_FUNCTIONS = ('captcha.helpers.post_smooth',)
CAPTCHA_PUNCTUATION = ''',;.!?'''

# VPS-specific captcha configuration
if PRODUCTION:
    # Production captcha settings for VPS
    CAPTCHA_CHALLENGE_FUNCTION = 'captcha.helpers.random_char_challenge'
    CAPTCHA_BACKGROUND_COLOR = '#ffffff'
    CAPTCHA_FOREGROUND_COLOR = '#000000'
    # Configure font path for VPS - try common Linux font locations
    import os
    
    # Try multiple font paths that might exist on the VPS
    potential_fonts = [
        '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
        '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf',
        '/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf',
        '/usr/share/fonts/TTF/DejaVuSans.ttf',
        '/System/Library/Fonts/Arial.ttf',  # macOS
        '/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf',
    ]
    
    CAPTCHA_FONT_PATH = None
    for font_path in potential_fonts:
        if os.path.exists(font_path):
            CAPTCHA_FONT_PATH = font_path
            break
    
    # If no font found, try to use a list of potential fonts
    if CAPTCHA_FONT_PATH is None:
        # Set a list of fonts for django-simple-captcha to try
        CAPTCHA_FONT_PATH = potential_fonts
        
    # Additional VPS-specific settings for better image generation
    CAPTCHA_LETTER_ROTATION = (-20, 20)  # Slight rotation for security
    CAPTCHA_FOREGROUND_COLOR = '#2c3e50'  # Dark blue-gray for better contrast
    CAPTCHA_BACKGROUND_COLOR = '#ecf0f1'  # Light gray background
    for font_path in potential_fonts:
        if os.path.exists(font_path):
            CAPTCHA_FONT_PATH = font_path
            break
    
    # If no font found, try to use a list of potential fonts
    if CAPTCHA_FONT_PATH is None:
        # Set a list of fonts for django-simple-captcha to try
        CAPTCHA_FONT_PATH = potential_fonts
else:
    # Development captcha settings
    CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
    CAPTCHA_BACKGROUND_COLOR = '#ffffff'
    CAPTCHA_FOREGROUND_COLOR = '#000000'

# Use default captcha URL generation - let Django handle it properly
# The custom URL override was causing the broken images

# Celery configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Manila'

# Celery Beat schedule for automatic reminders
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'send-appointment-reminders-every-10-minutes': {
        'task': 'appointments.tasks.send_appointment_reminders_task',
        'schedule': crontab(minute='*/10'),
    },
}
