# Generated by Django 4.2.20 on 2025-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_appointment_type_appointment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='type',
            new_name='appointment_type',
        ),
    ]
