# Generated by Django 4.2.20 on 2025-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_rename_type_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Routine Check-up', 'Routine Check-up'), ('Vaccination', 'Vaccination'), ('Lab Test', 'Lab Test'), ('Physical Examination', 'Physical Examination')], default='Consultation', max_length=50),
        ),
    ]
