# Generated by Django 5.2.3 on 2025-07-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
