# Generated by Django 5.2.3 on 2025-07-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
    ]
