# Generated by Django 5.2.3 on 2025-08-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_remove_notes_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
