# Generated by Copilot: Remove 'reason' field from Appointment model
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
    ]
