# Generated by Django 5.2.5 on 2025-09-10 03:11

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_remove_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
