# Generated by Django 5.2.5 on 2025-09-10 03:17

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_encrypt_appointment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_birth',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='marital_status',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
