# Generated by Django 5.2.5 on 2025-09-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_appointment_patient_id_lookup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id_lookup',
        ),
    ]
