# Generated by Django 5.2.3 on 2025-10-16 19:19

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_fix_encrypted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='religion',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
