# Generated by Django 5.2.5 on 2026-02-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmation_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='email', max_length=10),
        ),
    ]
