class ClinicSettings(models.Model):
    # ... existing fields ...
    primary_color = models.CharField(max_length=7, default="#1976d2")  # Default blue
    logo = models.ImageField(upload_to='branding/', null=True, blank=True)
    # ... existing code ... 