# Generated by Django 4.2.20 on 2025-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='HealthNexus Medical Center', max_length=255)),
                ('address', models.CharField(default='123 Health Avenue, Medical District', max_length=255)),
                ('city', models.CharField(default='Cityville', max_length=100)),
                ('state', models.CharField(default='California', max_length=100)),
                ('zip', models.CharField(default='12345', max_length=20)),
                ('phone', models.CharField(default='(123) 456-7890', max_length=20)),
                ('email', models.EmailField(default='info@healthnexus.com', max_length=254)),
                ('website', models.CharField(default='www.healthnexus.com', max_length=255)),
                ('primary_color', models.CharField(default='#1976d2', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
        ),
    ]
