# Generated by Django 4.2.20 on 2025-06-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='about_text',
            field=models.TextField(default='Founded in 2010, HealthNexus has grown to become one of the leading healthcare providers in the region. Our mission is to deliver accessible, high-quality healthcare services in a compassionate environment.'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='about_title',
            field=models.CharField(default='About Our Clinic', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='hero_subtitle',
            field=models.TextField(default='Our clinic is dedicated to providing exceptional healthcare services with a patient-centered approach. Schedule your appointment today.'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='hero_title',
            field=models.CharField(default='Your Health Is Our Priority', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.clinicsettings')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='clinic.clinicsettings')),
            ],
        ),
    ]
