# Generated by Django 4.2.20 on 2025-06-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinicsettings_about_text_clinicsettings_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic_building_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='healthcare_professionals_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
