# Generated by Django 5.2.3 on 2025-07-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicsettings_clinic_building_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clinicsettings',
            table='clinic_settings',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
