# Generated by Django 5.2.3 on 2025-07-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinicsettings_table_alter_faq_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faqs',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
