# Generated by Django 5.2.3 on 2025-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_faq_table_alter_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL for the clinic location', max_length=1000, null=True),
        ),
    ]
