# Generated by Django 4.2.20 on 2025-05-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
    ]
