# Generated by Django 4.2.20 on 2025-05-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_availability', '0002_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='predefined_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_availability.predefinedtimeslot'),
        ),
    ]
