# Generated by Django 4.2.20 on 2025-05-29 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_availability', '0003_predefinedtimeslot_alter_doctoravailability_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='predefined_slot',
        ),
        migrations.AddField(
            model_name='predefinedtimeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predefinedtimeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='max_appointments',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
