# Generated by Django 5.2.3 on 2025-07-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_availability', '0004_remove_timeslot_predefined_slot_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctoravailability',
            table='doctor_availability',
        ),
        migrations.AlterModelTable(
            name='predefinedtimeslot',
            table='predefined_time_slot',
        ),
        migrations.AlterModelTable(
            name='timeslot',
            table='time_slot',
        ),
    ]
