# Generated by Django 4.2.20 on 2025-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
