# Generated by Django 4.2.20 on 2025-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_appointments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_clinic_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_patients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
