# Generated by Django 5.2.3 on 2025-08-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_access_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_access_security_testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_usage_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor')], default='doctor', max_length=20),
        ),
    ]
