# Generated by Django 5.2.5 on 2025-09-09 23:52

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_create_default_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=security_app.fields.EncryptedCharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
