# Generated by Django 5.2.5 on 2025-09-10 00:23

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=security_app.fields.EncryptedCharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
