# Generated by Django 5.2.5 on 2025-09-10 02:14

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=450),
        ),
    ]
