# Generated by Django 5.2.5 on 2025-09-10 02:17

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_encrypt_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
