# Generated by Django 5.2.5 on 2025-10-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_encrypted_name_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='middle_initial',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='suffix',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
