# Generated by Django 5.2.3 on 2025-10-09 12:30

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_inventory_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
