# Generated by Django 5.2.3 on 2025-11-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_license_number_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_access_integrations',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_access_security_testing',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_view_usage_reports',
        ),
    ]
