# Generated by Django 5.2.5 on 2025-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_mark_default_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_default_account',
            field=models.BooleanField(default=False),
        ),
    ]
