# Generated by Django 5.2.5 on 2025-12-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_customuser_is_default_account'),
        ('accounts', '0024_remove_superadmin_patient_appointment_permissions'),
    ]

    operations = [
    ]
