# Generated by Django 5.2.5 on 2025-12-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_merge_20251204_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
