# Generated by Django 4.2.20 on 2025-07-09 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('receptionist_approved', 'Receptionist Approved'), ('doctor_approved', 'Doctor Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('receptionist_approved_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prescription_content', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('doctor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_approved_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('receptionist_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('sick_leave', 'Sick Leave Certificate'), ('fitness', 'Medical Fitness Certificate'), ('vaccination', 'Vaccination Certificate'), ('general', 'General Medical Certificate')], max_length=20)),
                ('patient_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('receptionist_approved', 'Receptionist Approved'), ('doctor_approved', 'Doctor Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('receptionist_approved_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_content', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('doctor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_approved_certificates', to=settings.AUTH_USER_MODEL)),
                ('receptionist_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
