# Generated by Django 5.2.3 on 2025-07-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicalcertificaterequest',
            table='medical_certificate_request',
        ),
        migrations.AlterModelTable(
            name='prescriptionrequest',
            table='prescription_request',
        ),
    ]
