# Generated by Django 5.2.3 on 2025-07-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_requests', '0002_alter_medicalcertificaterequest_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='id_verification',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/id_verification/'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='id_verification',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/id_verification/'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='prescription_image',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/prescriptions/'),
        ),
    ]
