# Generated by Django 5.2.3 on 2025-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_requests', '0003_medicalcertificaterequest_id_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='id_verification_back',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/id_verification/'),
        ),
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='id_verification_front',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/id_verification/'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='id_verification_back',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/id_verification/'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='id_verification_front',
            field=models.FileField(blank=True, null=True, upload_to='medical_requests/id_verification/'),
        ),
    ]
