# Generated by Django 5.2.5 on 2025-09-10 03:29

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_requests', '0004_add_separate_id_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='additional_info',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='certificate_content',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='date_of_birth',
            field=security_app.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='doctor_notes',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='email',
            field=security_app.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='patient_name',
            field=security_app.fields.EncryptedCharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='phone',
            field=security_app.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='rejection_reason',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='additional_notes',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='date_of_birth',
            field=security_app.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='doctor_notes',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='dosage',
            field=security_app.fields.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='duration',
            field=security_app.fields.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='email',
            field=security_app.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='frequency',
            field=security_app.fields.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='medication_name',
            field=security_app.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='patient_name',
            field=security_app.fields.EncryptedCharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='phone',
            field=security_app.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='prescription_content',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='rejection_reason',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
