# Generated by Django 5.2.3 on 2025-10-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_requests', '0005_alter_medicalcertificaterequest_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup from Clinic'), ('email', 'Send via Email')], default='pickup', max_length=10),
        ),
    ]
