# Generated by Django 5.2.5 on 2025-12-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_requests', '0006_medicalcertificaterequest_delivery_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcertificaterequest',
            old_name='receptionist_approved_at',
            new_name='on_process_at',
        ),
        migrations.RenameField(
            model_name='prescriptionrequest',
            old_name='receptionist_approved_at',
            new_name='on_process_at',
        ),
        migrations.RemoveField(
            model_name='medicalcertificaterequest',
            name='receptionist_approved_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionrequest',
            name='receptionist_approved_by',
        ),
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='on_process_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_process_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcertificaterequest',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='on_process_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_process_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalcertificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_process', 'On Process'), ('doctor_approved', 'Doctor Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='prescriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_process', 'On Process'), ('doctor_approved', 'Doctor Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
    ]
