BEGIN;
--
-- Create model ClinicSettings
--
CREATE TABLE "clinic_clinicsettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "clinic_name" varchar(255) NOT NULL, "address" varchar(255) NOT NULL, "city" varchar(100) NOT NULL, "state" varchar(100) NOT NULL, "zip" varchar(20) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "website" varchar(255) NOT NULL, "primary_color" varchar(7) NOT NULL, "logo" varchar(100) NULL);
COMMIT;
