# Generated by Django 4.2.20 on 2025-06-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_physical_examination'),
        ('patients', '0007_patient_physical_examination'),
    ]

    operations = [
    ]
