# Generated by Django 5.2.3 on 2025-07-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_merge_20250628_0040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
