# Generated by Django 5.2.3 on 2025-07-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
