# Generated by Django 5.2.3 on 2025-08-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patient_patient_id'),
    ]

    operations = [
    ]
