# Generated by Django 5.2.3 on 2025-08-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_populate_patient_ids'),
    ]

    operations = [
    ]
