# Generated by Django 5.2.3 on 2025-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_populate_patient_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
