# Generated by Django 5.2.5 on 2025-09-09 23:52

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=security_app.fields.EncryptedCharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_info',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_initial',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=security_app.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physical_examination',
            field=security_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suffix',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
