# Generated by Django 5.2.5 on 2025-09-10 00:11

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_patient_address_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=security_app.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_initial',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=security_app.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suffix',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
