# Generated by Django 5.2.5 on 2025-12-04 01:38

import django.db.models.deletion
import security_app.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_red_flagged',
            field=models.BooleanField(default=False, help_text='Mark patient as red flagged for special attention'),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_flag_reason',
            field=security_app.fields.EncryptedTextField(blank=True, help_text='Reason for red flagging this patient', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_flagged_by',
            field=models.ForeignKey(blank=True, help_text='User who red flagged this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_flagged_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_flagged_date',
            field=models.DateTimeField(blank=True, help_text='When the patient was red flagged', null=True),
        ),
    ]
