# Generated by Django 5.2.5 on 2026-02-02 13:28

import django.db.models.deletion
import security_app.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_patient_is_red_flagged_patient_red_flag_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_reason',
            field=security_app.fields.EncryptedTextField(blank=True, help_text='Reason for archiving this patient', null=True),
        ),
    ]
