# Generated by Django 5.2.3 on 2025-08-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('BULK_OPERATION', 'Bulk Operation'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=20)),
                ('resource_type', models.CharField(choices=[('USER', 'User'), ('PATIENT', 'Patient'), ('APPOINTMENT', 'Appointment'), ('PRESCRIPTION', 'Prescription'), ('MEDICAL_DOCUMENT', 'Medical Document'), ('MEDICAL_REQUEST', 'Medical Request'), ('STAFF', 'Staff'), ('CLINIC_SETTINGS', 'Clinic Settings'), ('PERMISSIONS', 'Permissions'), ('AUTHENTICATION', 'Authentication'), ('SYSTEM', 'System')], max_length=20)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['resource_type'], name='audit_logs_resourc_e11e1b_idx'), models.Index(fields=['resource_id'], name='audit_logs_resourc_5afa9a_idx')],
            },
        ),
    ]
