# Generated by Django 5.2.5 on 2025-10-06 20:57

import django.db.models.deletion
import security_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', security_app.fields.EncryptedCharField(max_length=200)),
                ('description', security_app.fields.EncryptedTextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('medication', 'Medication'), ('supplies', 'Medical Supplies'), ('equipment', 'Equipment'), ('other', 'Other')], default='medication', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', security_app.fields.EncryptedCharField(default='pieces', max_length=50)),
                ('minimum_stock', models.IntegerField(default=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired')], default='in_stock', max_length=20)),
                ('batch_number', security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', security_app.fields.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('supplier_contact', security_app.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference', security_app.fields.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('notes', security_app.fields.EncryptedTextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventory')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
