# Generated by Django 5.2.5 on 2025-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicinerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecord',
            name='alert_months_before',
            field=models.IntegerField(choices=[(2, '2 months before'), (3, '3 months before'), (4, '4 months before'), (5, '5 months before'), (6, '6 months before'), (7, '7 months before'), (8, '8 months before')], default=3, help_text='Alert this many months before expiration'),
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='Current quantity in stock'),
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Medicine expiration date', null=True),
        ),
        migrations.AddField(
            model_name='medicinerecord',
            name='minimum_stock_alert',
            field=models.IntegerField(default=10, help_text='Alert when stock goes below this number'),
        ),
    ]
