# Generated by Django 5.2.5 on 2025-12-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicinerecord_alert_months_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerecord',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='medicinerecord',
            name='minimum_stock_alert',
        ),
    ]
