# Generated by Django 5.2.3 on 2025-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AWS Textract Config', max_length=100, unique=True)),
                ('aws_access_key_id', models.CharField(help_text='AWS Access Key ID', max_length=200)),
                ('aws_secret_access_key', models.CharField(help_text='AWS Secret Access Key', max_length=200)),
                ('aws_region', models.CharField(default='us-east-1', help_text='AWS Region', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Use these credentials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AWS Credentials',
                'verbose_name_plural': 'AWS Credentials',
            },
        ),
    ]
