# Generated by Django 5.2.3 on 2025-07-25 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('differential', 'Differential Backup')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EncryptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_type', models.CharField(choices=[('database', 'Database Encryption'), ('files', 'File System Encryption'), ('communication', 'Communication Encryption'), ('backup', 'Backup Encryption')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('algorithm', models.CharField(blank=True, max_length=50)),
                ('key_strength', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('system', 'System Security Audit'), ('data', 'Data Protection Audit'), ('access', 'Access Control Audit'), ('backup', 'Backup System Audit'), ('encryption', 'Encryption Status Audit')], max_length=20)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('audit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0, help_text='Audit score out of 100')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('breach', 'Data Breach'), ('unauthorized_access', 'Unauthorized Access'), ('malware', 'Malware Detection'), ('phishing', 'Phishing Attempt'), ('ddos', 'DDoS Attack'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('require_special_chars', models.BooleanField(default=True)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=15)),
                ('enable_audit_logging', models.BooleanField(default=True)),
                ('audit_retention_days', models.IntegerField(default=365)),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_frequency_hours', models.IntegerField(default=24)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('encryption_algorithm', models.CharField(default='AES-256', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
    ]
