# Generated by Django 4.2.20 on 2025-06-29 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0008_merge_20250628_0040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('lab_result', 'Lab Result'), ('soap_note', 'SOAP Note'), ('prescription', 'Prescription'), ('clinical_note', 'Clinical Note'), ('medical_certificate', 'Medical Certificate'), ('physical_examination', 'Physical Examination'), ('imaging_report', 'Imaging Report'), ('discharge_summary', 'Discharge Summary'), ('referral_letter', 'Referral Letter'), ('consultation_note', 'Consultation Note')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('revised', 'Revised'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='medical_documents/originals/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='medical_documents/processed/')),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('access_notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's reported symptoms and concerns")),
                ('objective', models.TextField(help_text='Observable findings, vital signs, examination results')),
                ('assessment', models.TextField(help_text='Clinical impression and diagnosis')),
                ('plan', models.TextField(help_text='Treatment plan and follow-up instructions')),
                ('vital_signs', models.JSONField(blank=True, default=dict)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('history_present_illness', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note_detail', to='medical_documents.medicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=100, unique=True)),
                ('medications', models.JSONField(default=list)),
                ('general_instructions', models.TextField(blank=True)),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('valid_until', models.DateField()),
                ('refills_allowed', models.PositiveIntegerField(default=0)),
                ('refills_remaining', models.PositiveIntegerField(default=0)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by', models.CharField(blank=True, max_length=255)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_detail', to='medical_documents.medicaldocument')),
                ('prescribing_physician', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_appearance', models.JSONField(blank=True, default=dict)),
                ('vital_signs', models.JSONField(blank=True, default=dict)),
                ('head_neck', models.JSONField(blank=True, default=dict)),
                ('cardiovascular', models.JSONField(blank=True, default=dict)),
                ('respiratory', models.JSONField(blank=True, default=dict)),
                ('abdominal', models.JSONField(blank=True, default=dict)),
                ('neurological', models.JSONField(blank=True, default=dict)),
                ('musculoskeletal', models.JSONField(blank=True, default=dict)),
                ('skin', models.JSONField(blank=True, default=dict)),
                ('other_systems', models.JSONField(blank=True, default=dict)),
                ('overall_impression', models.TextField(blank=True)),
                ('abnormal_findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_examination_detail', to='medical_documents.medicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('fitness', 'Fitness Certificate'), ('disability', 'Disability Certificate'), ('sick_leave', 'Sick Leave Certificate'), ('work_clearance', 'Work Clearance'), ('travel_clearance', 'Travel Clearance'), ('sports_clearance', 'Sports Clearance'), ('school_clearance', 'School Clearance'), ('vaccination', 'Vaccination Certificate'), ('other', 'Other')], max_length=50)),
                ('purpose', models.CharField(max_length=255)),
                ('medical_opinion', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('restrictions', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificate_detail', to='medical_documents.medicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_category', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('cardiology', 'Cardiology'), ('endocrinology', 'Endocrinology'), ('toxicology', 'Toxicology'), ('molecular', 'Molecular Biology'), ('genetics', 'Genetics'), ('other', 'Other')], max_length=50)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('saliva', 'Saliva'), ('csf', 'Cerebrospinal Fluid'), ('tissue', 'Tissue'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('other', 'Other')], max_length=50)),
                ('laboratory_name', models.CharField(blank=True, max_length=255)),
                ('laboratory_address', models.TextField(blank=True)),
                ('lab_reference_number', models.CharField(blank=True, max_length=100)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('reported_date', models.DateTimeField(blank=True, null=True)),
                ('test_results', models.JSONField(default=list)),
                ('critical_values', models.JSONField(default=list)),
                ('abnormal_values', models.JSONField(default=list)),
                ('interpretation', models.TextField(blank=True)),
                ('clinical_significance', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('specimen_quality', models.CharField(blank=True, max_length=100)),
                ('processing_notes', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result_detail', to='medical_documents.medicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content_snapshot', models.JSONField()),
                ('changes_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical_documents.medicaldocument')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_documents/attachments/')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('report', 'Report'), ('scan', 'Scanned Document'), ('xray', 'X-Ray'), ('lab_report', 'Lab Report'), ('prescription_image', 'Prescription Image'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_documents.medicaldocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'Viewed'), ('edit', 'Edited'), ('delete', 'Deleted'), ('download', 'Downloaded'), ('print', 'Printed'), ('share', 'Shared')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='medical_documents.medicaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('consultation', 'Consultation Note'), ('discharge', 'Discharge Note'), ('follow_up', 'Follow-up Note'), ('telephone', 'Telephone Note'), ('referral', 'Referral Note'), ('procedure', 'Procedure Note'), ('general', 'General Note')], default='general', max_length=50)),
                ('clinical_context', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note_detail', to='medical_documents.medicaldocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'document_type'], name='medical_doc_patient_6fe4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['document_date'], name='medical_doc_documen_b8c5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['status'], name='medical_doc_status_0aeecd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['created_by'], name='medical_doc_created_f9d9ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
