# Generated by Django 5.2.3 on 2025-07-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicaldocument',
            new_name='medical_doc_patient_148679_idx',
            old_name='medical_doc_patient_6fe4ef_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaldocument',
            new_name='medical_doc_documen_39e067_idx',
            old_name='medical_doc_documen_b8c5a0_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaldocument',
            new_name='medical_doc_status_d07af4_idx',
            old_name='medical_doc_status_0aeecd_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaldocument',
            new_name='medical_doc_created_718442_idx',
            old_name='medical_doc_created_f9d9ab_idx',
        ),
        migrations.AlterModelTable(
            name='clinicalnote',
            table='clinical_note',
        ),
        migrations.AlterModelTable(
            name='documentaccesslog',
            table='document_access_log',
        ),
        migrations.AlterModelTable(
            name='documentattachment',
            table='document_attachment',
        ),
        migrations.AlterModelTable(
            name='documentversion',
            table='document_version',
        ),
        migrations.AlterModelTable(
            name='labresult',
            table='lab_result',
        ),
        migrations.AlterModelTable(
            name='medicalcertificate',
            table='medical_certificate',
        ),
        migrations.AlterModelTable(
            name='medicaldocument',
            table='medical_document',
        ),
        migrations.AlterModelTable(
            name='physicalexamination',
            table='physical_examination',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescription',
        ),
        migrations.AlterModelTable(
            name='soapnote',
            table='soap_note',
        ),
    ]
