# Generated by Django 5.2.5 on 2025-09-09 23:52

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_documents', '0002_rename_medical_doc_patient_6fe4ef_idx_medical_doc_patient_148679_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='clinical_context',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='findings',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='recommendations',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='abnormal_values',
            field=security_app.fields.EncryptedTextField(default=list),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='clinical_significance',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='critical_values',
            field=security_app.fields.EncryptedTextField(default=list),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='interpretation',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='lab_reference_number',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='laboratory_address',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='laboratory_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='processing_notes',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='recommendations',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='specimen_quality',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=security_app.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_results',
            field=security_app.fields.EncryptedTextField(default=list),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='access_notes',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='content',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='description',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='extracted_data',
            field=security_app.fields.EncryptedTextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='metadata',
            field=security_app.fields.EncryptedTextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='structured_data',
            field=security_app.fields.EncryptedTextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='title',
            field=security_app.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='general_instructions',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=security_app.fields.EncryptedTextField(default=list),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy_notes',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='assessment',
            field=security_app.fields.EncryptedTextField(help_text='Clinical impression and diagnosis'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='chief_complaint',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='history_present_illness',
            field=security_app.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='objective',
            field=security_app.fields.EncryptedTextField(help_text='Observable findings, vital signs, examination results'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='plan',
            field=security_app.fields.EncryptedTextField(help_text='Treatment plan and follow-up instructions'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='subjective',
            field=security_app.fields.EncryptedTextField(help_text="Patient's reported symptoms and concerns"),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='vital_signs',
            field=security_app.fields.EncryptedTextField(blank=True, default=dict),
        ),
    ]
