# Generated by Django 5.2.5 on 2025-09-10 00:23

import security_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_documents', '0003_alter_clinicalnote_clinical_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='lab_reference_number',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='laboratory_name',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='specimen_quality',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=security_app.fields.EncryptedCharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='title',
            field=security_app.fields.EncryptedCharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='chief_complaint',
            field=security_app.fields.EncryptedCharField(blank=True, max_length=800),
        ),
    ]
