# Generated by Django 5.2.5 on 2025-09-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_documents', '0005_remove_lab_result_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='medical_opinion',
            field=models.TextField(blank=True, default='Medical examination completed'),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='purpose',
            field=models.CharField(blank=True, default='General medical certificate', max_length=255),
        ),
    ]
