# Generated by Django 5.2.5 on 2025-11-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_documents', '0006_alter_medicalcertificate_medical_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='test_category',
            field=models.CharField(blank=True, choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('cardiology', 'Cardiology'), ('endocrinology', 'Endocrinology'), ('toxicology', 'Toxicology'), ('molecular', 'Molecular Biology'), ('genetics', 'Genetics'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
