# Generated by Django 5.2.5 on 2025-11-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_documents', '0007_alter_labresult_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='test_category',
        ),
    ]
